# Generated by Django 6.1 on 2026-09-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when article was approved.', null=True),
        ),
    ]
