# Generated by Django 6.1 on 2026-09-02 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_approved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'publisher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publisher_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
