# Generated by Django 6.1 on 2026-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_publisher_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('editor', 'editor'), ('journalist', 'Journalist'), ('publisher', 'Publisher')], default='reader', help_text="User's role in the system", max_length=20),
        ),
    ]
