# Generated by Django 6.1 on 2026-09-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(help_text='Each email address may only be used to register one user account.', max_length=254, unique=True, verbose_name='email'),
        ),
    ]
