# Generated by Django 6.1 on 2026-08-24 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
